package Server;

import java.util.*;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class Info {
	public int cloaktimer = 0;
	public boolean iscloaked = false;
	/* this data is given for every bot */
        public int id=-1;
        public double x=-1, y=-1;
        public double speed=-1, dir=-1;
        public double health=-1;

	/* the following is for your bot only */
        public double battery=-1;
        public double gunheat=-1;

        public int times_collided=0;
        public int times_hit=0;
	/* bots that have collided with or have hit you */
        public Vector collidelist;
        public Vector hitlist;

        public Info(int i, double a, double b, double h) {
		id = i;
		x = a; y = b;
		health = h;
	}

}
