package Server;

import java.util.*;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class Projectile {
	/* For smart bombs, once we implement it... */
	/*public Thread thread;*/
	/*public ProjectileHandler handler;*/
        public double x1;
        public double y1;
        public double x0;
        public double y0;
        public double px, py;
	int id;
        public int damage=1;
        public double speed=40.0f;
	public boolean isLive=true;

        public int times_hit=0;
        public Vector hitlist;

        public int objID;
	public int ownerbotid;
        public String ownerBotName;
        public double owner_x, owner_y;

        /* direction vector */
        public double vx, vy;
        public double dir;

public Projectile ( int ownerBotID, double direction, double x, double y) {
	isLive=true;
	ownerbotid = ownerBotID;
	dir = direction;
	x0 = x;
	y0 = y;
        hitlist = new Vector();
}

}
