
package Visualizer;


import java.awt.Dimension;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class MapObject {
        public int x, y;
	public int x0, y0;
        public String name;

        public int ID;
        public double dir_x, dir_y;
        public double scan1_x, scan1_y;
        public double scan2_x, scan2_y;

        public double scan_dir;
        public double scan_arc;

        public double health;
        public boolean hit;
	public boolean iscloaked;
}
