package Bot;

import Server.*;
import java.util.*;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class Hunter extends Bot {

public Hunter() {
	super();
        super.name = "Hunter";
}

public void ai() {
        int notargets=0;
        boolean notarget=true;
        boolean targetfound=false;
        int targetID=-1;
        double x, y;
        double dist;
        double x0=0, y0=0;
        double dir=0;
        Vector infolist;
        Info info;
        Info me;

        System.out.println("The Hunter is running.");
//        super.Drive((double) (java.lang.Math.random()*2*java.lang.Math.PI));
        
        while (true) {
                infolist = super.Scan(dir);
                me = (Info) infolist.elementAt(0);
//                if (infolist.size() == 1) {
		if (!targetfound) {
//                        System.out.println("Hunter: no one scanned at " + double.toString(dir*180.0f/ (double) java.lang.Math.PI) );
                        super.Drive(0, 0, 0);
                        dir += java.lang.Math.PI/20;
                }

                targetfound=false;
                for (int i=1; i < infolist.size(); i++) {
//                        System.out.println("Hunter: found someone at "
//                                + double.toString(dir*180.0f/ (double) java.lang.Math.PI) );

                        info = (Info) infolist.elementAt(i);
                        if (info.id < 0) break;

                        if (notarget) {
                                targetID = info.id;
//                                System.out.println("Hunter: New target bot" + Integer.toString(targetID)
//                                        + " at " + double.toString(dir*180.0f/ (double) java.lang.Math.PI) );
                                targetfound=true;
                                notarget=false;

                        } else if (info.id != targetID) {
//                                System.out.println("Hunter: Skipping bot" + Integer.toString(info.id) );
                                continue;
                        }

                        /* info.id == targetID */
//                        System.out.println("Hunter: Target bot" + Integer.toString(targetID) + " found.");
                        targetfound=true;

                        x = info.x - me.x;
                        y = info.y - me.y;
                        dist = (double) java.lang.Math.sqrt(x*x + y*y);

                        dir = arctan(x, y);

                        if (x0 == 0 && y0 == 0) super.Fire(x, y);
                        else super.Fire(x+5*(x0-x), y+5*(y0-y));
                        if (dist > 20) super.Drive(x+50, y+50, 10);
                        else super.Drive(x+50, y+50, info.speed);
                        x0 = x;
                        y0 = y;
                }
                if (!targetfound) {
                        if (notargets++ > 30) {
//                                System.out.println("Hunter: Target bot" + Integer.toString(targetID) + " can't be found -- looking for new target.");
                                notarget=true;
                                notargets=0;
                        }
                } else {
                        notargets=0;
                }
	  }
}


}
