import Bot.*;
import Server.*;
import java.util.*;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class ColliderIII extends Bot {

public ColliderIII() {
	super();
        super.name = "ColliderIII";
}

public void ai() {
        int notargets=0;
	boolean gethealth=false;
	boolean targethealth=false;
        boolean notarget=true;
        boolean targetfound=false;
        int targetID=-1;
        double x, y;
        double dir=0;
        Vector infolist;
        Info info;
        Info me;

//        super.Drive((double) (java.lang.Math.random()*2*java.lang.Math.PI));
        
        while (true) {
                infolist = Scan(dir);
                me = (Info) infolist.elementAt(0);

		if (targethealth || gethealth) {
			if (me.health >= 50) {
				targethealth=false;
				gethealth=false;
			}
		}

                if (!targetfound || gethealth && !targethealth) {
                        Drive(0, 0, 0);
                        dir -= java.lang.Math.PI/8;
                }

                targetfound=false;
                for (int i=1; i < infolist.size(); i++) {
                        info = (Info) infolist.elementAt(i);
			if (info.id < 0 && (me.health < 50 || gethealth)) {
				if (info.id == HEALTH) {
					x = info.x - me.x;
					y = info.y - me.y;
					Drive(x, y, 5);
					dir = arctan(x, y);
					targethealth=true;
					break;
				}
				continue;
			} else if (info.id < 0) break;

                        if (notarget && !gethealth) {
				/* don't hunt bots with more health than you */
				if (info.health > me.health) continue;
                                targetID = info.id;
				System.out.println("My target is " + Integer.toString(targetID) );
                                targetfound=true;
				notarget=false;
                        } else if (info.id != targetID) {
				continue;
                        }

			if (me.health < 50 || info.health > me.health) {
				notarget = true;
				if (me.health < 50) gethealth = true;
				continue;
			} else {
				targethealth=false;
				gethealth=false;
			}
			targetfound=true;
                        x = info.x - me.x;
                        y = info.y - me.y;
                        dir = arctan(x, y);
                        Drive(x, y, 20);
                }
                if (!targetfound) {
                        if (notargets++ > 10) {
                                notarget=true;
                                notargets=0;
                        }
                } else {
                        notargets=0;
                }
	  }
}


}
